# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:boron-browsers # Node 6 LTS
      - image: circleci/postgres:9.6
        environment:
          POSTGRES_USER: pguser
          POSTGRES_DB: app_test
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - node-{{ .Branch }}-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - node-

      - run: 
          name: "Install deps"
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: node-{{ .Branch }}-{{ checksum "yarn.lock" }}
        
      - run: 
          command: yarn db:migrate:latest
          environment:
            DATABASE_URL: postgres://pguser:@localhost:5432/app_test

      # run tests!
      - run: 
          name: "Unit tests"
          command: yarn test:unit
          environment:
            DATABASE_URL: postgres://pguser:@localhost:5432/app_test

      - run: 
          name: "Acceptance tests"
          command: BUILD=1 yarn test:acceptance
          environment:
            DATABASE_URL: postgres://pguser:@localhost:5432/app_test

      - run: 
          name: "Lint"
          command: yarn lint